### ISSUE TITLE
kontol tio basah

### ISSUE THREAD

**Issue by verdihatorou** [BOTCAHX/Hoream-MD#3]
anjay hp gw rusak tio tunggu gw beli hp baru ngoding lagi kita

**Comment by BOTCAHX** [comment]
kamu bohong aku tidak percaya

**Comment by verdihatorou** [comment]
beneran co 🙂 lgi ngumpulin duit mau beli hp baru ini hp gw yang kecil ga suport donlot wa

**Comment by verdihatorou** [comment]
oh iya lu buat nih bot sama siapa

**Comment by verdihatorou** [comment]
> > oh iya lu buat nih bot sama siapa
> 
> gua recode aja si

Si kang rekode

**Comment by verdihatorou** [comment]
Ready dah ada hp baru gw. :v gw bakal balik ngebot
