### ISSUE TITLE
Tio Jahat 🗿

### ISSUE THREAD

**Issue by ERLANRAHMAT** [BOTCAHX/Hoream-MD#5]
Kasian yg nomornya ada di index di spam bot awok² 🗿🤣

**Comment by BOTCAHX** [comment]
🥇

**Comment by verdihatorou** [comment]
si erlan anjay sepuh

**Comment by ERLANRAHMAT** [comment]
> si erlan anjay sepuh

Bukan gw bukan sepuh 🗿
